export const TABLE_RESIZE = 'TABLE_RESIZE'
export const CHANGE_TEXT = 'CHANGE_TEXT'
export const APPLY_STYLES = 'APPLY_STYLES'
export const CHANGE_STYLES = 'CHANGE_STYLES'
export const CHANGE_HEADER = 'CHANGE_HEADER'
export const FORMULA = 'FORMULA'
export const UPDATE_DATE = 'UPDATE_DATE'
export const CLEAR_STATE = 'CLEAR_STATE'
export const CLEAR_STYLES = 'CLEAR_STYLES'
export const SORT_ROWS = 'SORT_ROWS'

